version: '3'
services:
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - fullstack_network

  backend:
    image: yafaorg/ai-assistant-backend:latest
    ports:
      - "11203:11203"
    environment:
      - GEMINI_API_KEY=your_gemini_api_key_here
      - SEARCH_ENGIN_ID=your_search_engine_id_here
      - GOOGLE_SEARCH_API_KEY=your_google_search_api_key_here
      - REDIS_HOST=redis://redis:6379  # Connects to the Redis service
    networks:
      - fullstack_network
    depends_on:
      - redis

  frontend:
    image: yafaorg/ai-assistant-ui:latest
    ports:
      - "3000:3000"
    networks:
      - fullstack_network

networks:
  fullstack_network:
    driver: bridge
